ApartmentListing/ApartmentListing/Controllers/ApartmentController.cs
using ApartmentListing.DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ApartmentListing.DAL.Services;

namespace ApartmentListing.Controllers
{
    public class ApartmentController : Controller
    {
        private ApartmentServices apartmentServices;

        public ApartmentController() 
        { 
           apartmentServices = new ApartmentServices();
        }

        // GET: /Apartment/
        [OutputCache(Duration = 1)]
        public ActionResult Index()
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            var apartments = apartmentServices.GetAllFormated();
            return View(apartments);
        }

        [OutputCache(Duration = 1)]
        public ActionResult FindByID(long Id) 
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            var apartment = apartmentServices.Details(Id);
            return View(apartment);
        }
	}
}

ApartmentListing/ApartmentListing/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApartmentListing.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<string> values = new List<string>();
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            return View();
        }

        public ActionResult Contact()
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;

            ViewBag.Message = "Please provide feedback on the application";
            return View();
        }

        public ActionResult UrlLog()
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            return View(values);
        }
    }
}

ApartmentListing/ApartmentListing/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ApartmentListing.DAL.Models;
using ApartmentListing.DAL.Services;

namespace ApartmentListing.Controllers
{
    public class SearchController : Controller
    {
        private ApartmentServices apartmentServices = new ApartmentServices();

        //
        // GET: /Search/
        [HttpGet]
        public ActionResult Index()
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Apartment apartment)
        {
          
            if (ModelState.IsValid)
            {
                var allSearchedApartments = apartmentServices.GetAllSearched(apartment);
                TempData["searchedList"] = allSearchedApartments;
                TempData["searchCriteriaAddress"] = apartment.Address;
                TempData["searchCriteriaCity"] = apartment.City;
                TempData["searchCriteriaSuburb"] = apartment.Suburb;
                return RedirectToAction("ViewSearchResult");
            }
           
            return View();
        }

        public ActionResult ViewSearchResult() 
        {
            var values = Session["urlLog"] as List<string>;
            var url = Request.Url.ToString();
            values.Add(url);
            Session["urlLog"] = values;
            var searchResults = TempData["searchedList"];
            ViewBag.searchedAddress = TempData["searchCriteriaAddress"];
            ViewBag.searchedCity = TempData["searchCriteriaCity"];
            ViewBag.searchedSuburb = TempData["searchCriteriaSuburb"];
            return View(searchResults);
        }
	}
}

ApartmentListing/ApartmentListing/Views/Apartment/FindByID.cshtml
@model ApartmentListing.DAL.Models.Apartment

<h2>Individual Listing</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Suburb)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Suburb)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rooms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rooms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bathrooms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bathrooms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Carports)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Carports)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to Apartment Listings", "Index")
</p>

ApartmentListing/ApartmentListing/Views/Apartment/Index.cshtml
@model IEnumerable<ApartmentListing.DAL.Models.Apartment>


<h2>Apartment List</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suburb)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rooms)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bathrooms)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Carports)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Suburb)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rooms)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bathrooms)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Carports)
        </td>
        <td>
            @Html.ActionLink("More Details", "FindByID", new { id = item.ID })
        </td>
    </tr>
}

</table>

ApartmentListing/ApartmentListing/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Page";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Shuvayu Dhar<br />
    <abbr title="Phone">P:</abbr>
    0431904071
</address>

<address>
    <strong>Email ID:</strong> <a href="mailto:shuvayu.dhar@gmail.com">shuvayu.dhar@gmail.com</a>
</address>

ApartmentListing/ApartmentListing/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET MVC Application</h1>
    <p class="lead">An ASP.NET MVC application for a listing of apartments solution.</p>
</div>

ApartmentListing/ApartmentListing/Views/Home/UrlLog.cshtml
@model List<string>
@{
    ViewBag.Title = "UrlLog";
}

<h2>Log of all the URLs visited by the User</h2>
<hr />
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
              @Html.DisplayFor(modelItem => item)<br />
        }
    </div>
</div>

ApartmentListing/ApartmentListing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apartment Listing Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Apartment Listing Application", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List of Apartments", "Index", "Apartment")</li>
                    <li>@Html.ActionLink("Search for Apartments", "Index", "Search")</li>
                    <li>@Html.ActionLink("Url Log", "urlLog", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Apartment Listing Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/js")
    @RenderSection("scripts", required: false)
</body>
</html>