ENET MVC/EnetMVC/DAL/DAL/Website/ViewModels/PackageViewModel.cs
using System;
using System.Collections.Generic;

namespace Website.ViewModels
{
    /// <summary>
    ///     Model package
    /// </summary>
    public class PackageViewModel
    {


        public int PackageId { get; set; }
        public virtual ICollection<DistributionViewModel> Distributions { get; set; }

        public virtual MedicineViewModel Medicine { get; set; }
        public int MedicineId { get; set; }
        public string BarcodeId { get; set; }
        public DateTime ExpiryDate { get; set; }
      
     
   
        public DateTime RegisteredOn { get; set; }

        public string TransitState { get; set; }
     
        public int PackageStatusId { get; set; }



        public int  RegisteredBy { get; set; }

        
        public int  RegisteredAt { get; set; }
       
        public int  CurrentLocationId { get; set; }

        public bool Found { get; set; }

        public virtual ICollection<PackageTransactionsViewModel> PackageTransactionses { get; set; }

    }
}

ENET MVC/EnetMVC/DAL/DAL/Website/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DAL.Models;
using Domain.Contracts;
using Newtonsoft.Json;
using Website.ViewModels;

namespace Website.Controllers
{
    public class MedicinesController : Controller
    {
        private MedicinesContracts medicineContracts;
        public MedicinesController()
        {
            medicineContracts = new MedicinesContracts();
        }
        // GET: Medicines
        public ActionResult Index()
        {
            AutoMapper.Mapper.CreateMap<Medicine, MedicineViewModel>();
            var medicines = Mapper.Map<IEnumerable<MedicineViewModel>>(medicineContracts.GetAll());
            return View(medicines);
        }


        public ActionResult AddMedicine()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMedicine(MedicineViewModel medicine)
        {
            if (ModelState.IsValid)
            {
                AutoMapper.Mapper.CreateMap<MedicineViewModel, Medicine>();
                var medicineModel = Mapper.Map<Medicine>(medicine);
                medicineContracts.Add(medicineModel);
                TempData["success"] = "Successfully added the medicine";
                return RedirectToAction("AddMedicine");
            }
            TempData["fail"] = "Failed to add the medicine";
            return View();
        }


        public ActionResult GetMedicine(int id)
        {
            var medicine = medicineContracts.Get(id);
            AutoMapper.Mapper.CreateMap<Medicine, MedicineViewModel>();
            AutoMapper.Mapper.CreateMap<Package, PackageViewModel>();
            var medicineVM = Mapper.Map<MedicineViewModel>(medicine);
            medicineVM.Expiry = DateTime.Now.AddDays(medicine.ShelfLife).ToShortDateString();
            return Json(medicineVM);
        }

        public ActionResult Delete(int id)
        {

            AutoMapper.Mapper.CreateMap<Medicine, MedicineViewModel>();
            var medicine = Mapper.Map<MedicineViewModel>(medicineContracts.Get(id));

            return View(medicine);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            medicineContracts.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ENET MVC/EnetMVC/DAL/DAL/Website/Controllers/PackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DAL.Models;
using Domain.Contracts;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Website.Models;
using Website.ViewModels;

namespace Website.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PackagesController : Controller
    {
        private PackagesContracts packagesContracts;
        private MedicinesContracts medicineContracts;
        private UserContracts userContracts;
        private DistributionCentersContracts dcContracts;
        private PackageTransactionsContracts packageTransactionsContracts;
        private DistributionsContracts distributionsContracts;
       public PackagesController()
        {
            packagesContracts = new PackagesContracts();
            medicineContracts = new MedicinesContracts();
            userContracts = new UserContracts();
            dcContracts= new DistributionCentersContracts();
            packageTransactionsContracts = new PackageTransactionsContracts();
            distributionsContracts = new DistributionsContracts();
        }
        // GET: Packages
        public ActionResult Index()
        {
            AutoMapper.Mapper.CreateMap<Package, PackageViewModel>();
            AutoMapper.Mapper.CreateMap<Medicine, MedicineViewModel>();
            AutoMapper.Mapper.CreateMap<PackageStatus, PackageStatusViewModel>();
            AutoMapper.Mapper.CreateMap<PackageTransactions, PackageTransactionsViewModel>();
            var user = User.Identity.GetUserName();
            var packagesModels = packagesContracts.GetAllPackagesAtDC(user);

            var packages = AutoMapper.Mapper.Map<IEnumerable<PackageViewModel>>(packagesModels);
            foreach (var VARIABLE in packages)
            {
                VARIABLE.TransitState =
                    packagesContracts.GetAllStatus().First(x => x.PackageStatusId == VARIABLE.PackageStatusId).TransitState;
            }
            return View(packages);
        }


        public ActionResult CreatePackage()
        {
            
            ViewBag.MedicineId = new SelectList(medicineContracts.GetAll(), "MedicineId", "MedicineName");
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult CreatePackage(PackageViewModel packageViewModel)
        {
            AutoMapper.Mapper.CreateMap<PackageViewModel,Package>();
            var packageModel = AutoMapper.Mapper.Map<Package>(packageViewModel);
      
            var userName= User.Identity.GetUserName();
            var enetUser =Enumerable.First(userContracts.GetAll(), x => x.UserName == userName);
           
            packageModel.RegisteredBy = enetUser.UserId;
            packageModel.RegisteredAt = enetUser.DistributionCenterId;
            ViewBag.MedicineId = new SelectList(medicineContracts.GetAll(), "MedicineId", "MedicineName");

           packageModel= packagesContracts.Add(packageModel);
            if (!String.IsNullOrEmpty(packageModel.BarcodeId))
            {

                ViewBag.URL= Barcode.Encode(packageModel.BarcodeId, Server.MapPath("~/Images/"));
                ViewBag.URL = "/Images/" + packageModel.BarcodeId + ".jpg";
                TempData["Success"] = "Package Create : Barcode :" + packageModel.BarcodeId;
                ViewBag.Barcode = packageModel.BarcodeId;
                return View(packageViewModel);
            }
            else
            {
                TempData["Fail"] = "Error Creating the barcode";
               return RedirectToAction("CreatePackage");
            }
            return View();
          
        }

        
        public ActionResult SendPackage()
        {
            LoadViewBags();
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SendPackage(string id)
        {
            AutoMapper.Mapper.CreateMap<Package, PackageViewModel>();
            var package= Mapper.Map<PackageViewModel>(packagesContracts.Get(id));
           LoadViewBags();
            return View(package);

        }


        public ActionResult GetPackageByBarcode(string id)
        {
            AutoMapper.Mapper.CreateMap<Package, PackageViewModel>();
            AutoMapper.Mapper.CreateMap<Medicine,MedicineViewModel>();
            AutoMapper.Mapper.CreateMap<PackageStatus,PackageStatusViewModel>();
            AutoMapper.Mapper.CreateMap<PackageTransactions,PackageTransactionsViewModel>();
            var user = User.Identity.GetUserName();
            ;
            var package = Mapper.Map<PackageViewModel>(packagesContracts.GetInStockInCurrentDC(id, userContracts.GetcurrentUserDetails(user).DistributionCenterId));
            if (package==null)
            {
                package= new PackageViewModel();
                LoadViewBags();
                package.PackageId=-1;
                return Json(package);
            }
            else
            {
                var medicine = package.Medicine;
                medicine.Expiry = package.ExpiryDate.ToShortDateString();
                return Json(medicine);    
            }
            
        }

        



        /// <summary>
        /// 
        /// </summary>
        /// <param name="packageTransactions"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendPackageWithModel(PackageViewModel packageViewModel)
        {
            AutoMapper.Mapper.CreateMap<PackageViewModel, Package>();
            AutoMapper.Mapper.CreateMap<PackageStatusViewModel, PackageStatus>();
            AutoMapper.Mapper.CreateMap<MedicineViewModel, Medicine>();
            var package=Mapper.Map<Package>(packageViewModel);
            
         var id=   packagesContracts.SendPackage(package,User.Identity.GetUserName());
            if (id>0)
            {
                TempData["Success"] = "Sent the package";
                return Redirect("SendPackage");
            }
            else
            {
               LoadViewBags();
                TempData["Fail"] = "Failed to send the package";
                return View("SendPackage");
            }


        }



        public ActionResult ReceivePackage()
        {
            return View();

        }  
        public ActionResult GetPackageForTransit(string barCode)
        {

            AutoMapper.Mapper.CreateMap<Package, PackageViewModel>();
            AutoMapper.Mapper.CreateMap<Medicine, MedicineViewModel>();
            AutoMapper.Mapper.CreateMap<PackageStatus, PackageStatusViewModel>();
            AutoMapper.Mapper.CreateMap<PackageTransactions, PackageTransactionsViewModel>();
            var user = User.Identity.GetUserName();
            var packagevm = packagesContracts.GetInTransitInCurrentDC(barCode,
                userContracts.GetcurrentUserDetails(user).DistributionCenterId);
            var package = Mapper.Map<PackageViewModel>(packagevm);
            if (package == null)
            {
                package = new PackageViewModel();
                LoadViewBags();
                package.PackageId = -1;
                return Json(package);
            }
            else
            {
                var medicine = package.Medicine;
                medicine.Expiry = package.ExpiryDate.ToShortDateString();
                return Json(medicine);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReceivePackagewithModel(PackageViewModel packageViewModel)
        {

            var package = packagesContracts.Get(packageViewModel.BarcodeId);
            // Change current loc to this loc
            //Transit state
           var id= packagesContracts.ReceivePackage(package, User.Identity.GetUserName());
            if (id>0)
            {
                TempData["Success"] = "Received Package";
                return RedirectToAction("ReceivePackage");

            }
            else
            {
                TempData["Fail"] = "Failed to receive";
                return View("ReceivePackage");
            }

        }
        public void LoadViewBags()
        {
            var user = userContracts.GetcurrentUserDetails(User.Identity.GetUserName());
            var dcs = dcContracts.GetExceptCurrentDC(user.DistributionCenterId);
            ViewBag.CurrentLocationId = new SelectList(dcs, "DistributionCenterId", "Name");
        }

       

     
    }
}

ENET MVC/EnetMVC/DAL/DAL/Website/Views/Packages/CreatePackage.cshtml
@model Website.ViewModels.PackageViewModel

@{
    ViewBag.Title = "CreatePackage";
}

<h2>CreatePackage</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PackageViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MedicineId,null,"--Select--", new { htmlAttributes = new { @class = "form-control" ,@id= "ddlmedicineId" }, })
                @Html.ValidationMessageFor(model => model.MedicineId, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.Medicine.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.LabelFor(model => model.Medicine.Description, new { htmlAttributes = new { @class = "form-control" },@id="lblmedicineDesc" })
                
            </div>
        </div>
     
      
        <div class="form-group">
            @Html.LabelFor(model => model.Medicine.Expiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" }, @id = "lblExpiry" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medicine.IstempSensitve, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.LabelFor(model => model.Medicine.IstempSensitve, new {htmlAttributes = new {@class = "form-control"}, @id = "lbltemp"})

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Medicine.Value, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.LabelFor(model => model.Medicine.Value, new {htmlAttributes = new {@class = "form-control"}, @id = "lblValue"})

            </div>
        </div>
        @if (TempData["Success"] != null)
        {
            <div class="form-group">
                <div>
                    <div class="alert alert-success">@TempData["Success"]
                        <img src="@ViewBag.URL" />  
                    </div>
                  
                  @*<img src="~/Content/8229196847.jpg" />*@
                  
                </div>
            </div>
        }
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('#MedicineId').change(function () {
            debugger;
            var selected = $('#MedicineId').val();
            $.post('@Url.Action("GetMedicine", "Medicines")', { id: selected }, function (data) {
                debugger;
                alert('pass');
                $('#lblmedicineDesc').text(data.Description);
                $('#lblExpiry').val(data.Expiry);
                $('#lbltemp').text(data.IstempSensitve);
                $('#lblValue').text(data.Value);
            });
        });
    </script>

    
    
}

ENET MVC/EnetMVC/DAL/DAL/Website/Views/Packages/Details.cshtml
@model Website.ViewModels.PackageViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PackageViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PackageId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicineId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicineId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BarcodeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarcodeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransitState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransitState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PackageStatusId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageStatusId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentLocationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentLocationId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ENET MVC/EnetMVC/DAL/DAL/Website/Views/Packages/Index.cshtml
@model IEnumerable<Website.ViewModels.PackageViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "CreatePackage")
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Medicine.MedicineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BarcodeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </th> 
        <th>
            @Html.DisplayNameFor(model => model.RegisteredOn)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.TransitState)
        </th>
       
     
     
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.Medicine.MedicineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BarcodeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiryDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegisteredOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransitState)
        </td>
       
        <td>
            @Html.ActionLink("Send Package", "SendPackage", new {  id=item.BarcodeId  }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

ENET MVC/EnetMVC/DAL/DAL/Website/Views/Packages/ReceivePackage.cshtml
@model Website.ViewModels.PackageViewModel

@{
    ViewBag.Title = "Receive Package";
}

<h2>SendPackage</h2>

<div>
    <h4>PackageViewModel</h4>
    <hr />

    @using (Html.BeginForm("ReceivePackagewithModel", "Packages"))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-4">Please scan the Bar Code</div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.BarcodeId, null, new { htmlAttributes = new { @class = "form-control", @id = "lblBarcode" }, })
                @Html.ValidationMessageFor(model => model.BarcodeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="details well" style="display: none">
            <div class="container">
                <dl class="dl-horizontal">


                    <dt>Name:</dt>
                    <dd>
                        @Html.LabelFor(model => model.Medicine.MedicineName, new { htmlAttributes = new { @class = "form-control" }, @id = "lblName" })
                    </dd>

                    <dt>Description:</dt>
                    <dd>
                        @Html.LabelFor(model => model.Medicine.Description, new { htmlAttributes = new { @class = "form-control" }, @id = "lblmedicineDesc" })
                    </dd>

                    <dt>Expiry:</dt>
                    <dd>
                        @Html.LabelFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" }, @id = "lblExpiry" })
                    </dd>
                    <dt>Is Temp Sensitive:</dt>
                    <dd>
                        @Html.LabelFor(model => model.Medicine.IstempSensitve, new { htmlAttributes = new { @class = "form-control" }, @id = "lbltemp" })
                    </dd>
                    <dt>Price :</dt>
                    <dd>
                        @Html.LabelFor(model => model.Medicine.Value, new { htmlAttributes = new { @class = "form-control" }, @id = "lblValue" })
                    </dd>
                  
                   

                </dl>




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Receive" class="btn btn-default" />
                    </div>
                </div>









            </div>
        </div>
    }
    @Html.Partial("~/Views/_AlertPartial.cshtml")



    <div style="display: none" class="alert alert-dismissable notfound alert-danger">
        Package Not Found!
    </div>



</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('#lblBarcode').change(function () {
            debugger;
            var selected = $('#lblBarcode').val();
            $.post('@Url.Action("GetPackageForTransit", "Packages")', { barcode: selected }, function (data) {
                debugger;
                if (data.PackageId===-1) {
                    $('.notfound').show();
                    return;
                }
                $('.details').show();
                $('#lblName').text(data.MedicineName);
                $('#lblmedicineDesc').text(data.Description);
                $('#lblExpiry').text(data.Expiry);
                $('#lbltemp').text(data.IstempSensitve);
                $('#lblValue').text(data.Value);
            });

        });
    </script>



}

ENET MVC/EnetMVC/DAL/DAL/Website/Views/Packages/SendPackage.cshtml
@model Website.ViewModels.PackageViewModel

@{
    ViewBag.Title = "SendPackage";
}

<h2>SendPackage</h2>

<div>
    <h4>PackageViewModel</h4>
    <hr />

  @using (Html.BeginForm("SendPackageWithModel", "Packages"))
  {
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-4">Please scan the Bar Code</div>
        <div class="col-md-8">
            @Html.EditorFor(model => model.BarcodeId, null, new { htmlAttributes = new { @class = "form-control", @id = "lblBarcode" }, })
            @Html.ValidationMessageFor(model => model.BarcodeId, "", new { @class = "text-danger" })
        </div>
    </div>

      <div class="details well" style="display: none">
          <div class="container">
              <dl class="dl-horizontal">


                  <dt>Name:</dt>
                  <dd>
                      @Html.LabelFor(model => model.Medicine.MedicineName, new {htmlAttributes = new {@class = "form-control"}, @id = "lblName"})
                  </dd>

                  <dt>Description:</dt>
                  <dd>
                      @Html.LabelFor(model => model.Medicine.Description, new {htmlAttributes = new {@class = "form-control"}, @id = "lblmedicineDesc"})
                  </dd>

                  <dt>Expiry:</dt>
                  <dd>
                      @Html.LabelFor(model => model.ExpiryDate, new {htmlAttributes = new {@class = "form-control"}, @id = "lblExpiry"})
                  </dd>
                  <dt>Is Temp Sensitive:</dt>
                  <dd>
                      @Html.LabelFor(model => model.Medicine.IstempSensitve, new {htmlAttributes = new {@class = "form-control"}, @id = "lbltemp"})
                  </dd>
                  <dt>Price :</dt>
                  <dd>
                      @Html.LabelFor(model => model.Medicine.Value, new {htmlAttributes = new {@class = "form-control"}, @id = "lblValue"})
                  </dd>
                  <dt>Send to :</dt>
                  <dd>
                      @Html.DropDownListFor(model => Model.CurrentLocationId, null, "--Select--", new {htmlAttributes = new {@class = "form-control", @id = "ddlLocationId"},})
                  </dd>

              </dl>




              <div class="form-group">
                  <div class="col-md-offset-2 col-md-10">
                      <input type="submit" value="Send Package" class="btn btn-default"/>
                  </div>
              </div>
          








          </div>
      </div>
  }
    @Html.Partial("~/Views/_AlertPartial.cshtml")


  
        <div style="display: none" class="alert alert-dismissable notfound alert-danger">
          Package Not Found!
        </div>


  
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('#lblBarcode').change(function () {
            debugger;
            var selected = $('#lblBarcode').val();
            $.post('@Url.Action("GetPackageByBarcode", "Packages")', { id: selected }, function (data) {
                debugger;
                if (data.PackageId===-1) {
                    $('.notfound').show();
                    return;
                }
                $('.details').show();
                $('#lblName').text(data.MedicineName);
                $('#lblmedicineDesc').text(data.Description);
                $('#lblExpiry').text(data.Expiry);
                $('#lbltemp').text(data.IstempSensitve);
                $('#lblValue').text(data.Value);
            });

        });
    </script>



}